// Copyright 2026 kvcache-ai. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

//! Types and low-level support for selective guest-memory pre-faulting.

use std::io;
#[cfg(target_arch = "x86_64")]
use std::mem::size_of;

#[cfg(target_arch = "x86_64")]
use kvm_bindings::kvm_pre_fault_memory;
use kvm_ioctls::VcpuFd;
use serde::{Deserialize, Serialize};

use crate::arch::GUEST_PAGE_SIZE;
use crate::vmm_config::instance_info::VmState;
#[cfg(target_arch = "x86_64")]
use crate::vstate::vcpu::VcpuResponse;
use crate::vstate::vcpu::{VcpuError, VcpuSendEventError};

#[cfg(target_arch = "x86_64")]
use vmm_sys_util::ioctl::ioctl_with_mut_ref;
#[cfg(target_arch = "x86_64")]
use vmm_sys_util::ioctl_iowr_nr;

/// Request number generated by `_IOWR(KVMIO, 0xd5, struct kvm_pre_fault_memory)`.
#[cfg(target_arch = "x86_64")]
pub const KVM_PRE_FAULT_MEMORY_IOCTL: u64 = 0xc040_aed5;

/// One guest-physical range to pre-fault.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PreFaultMemoryRange {
    /// Starting guest physical address.
    pub gpa: u64,
    /// Number of bytes in the range.
    pub size: u64,
}

/// Request body for the pre-fault-memory API.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PreFaultMemoryRequest {
    /// Ranges to pre-fault, in the order supplied by the caller.
    pub ranges: Vec<PreFaultMemoryRange>,
}

/// Aggregate size information for a validated pre-fault request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PreFaultMemoryStats {
    /// Total bytes across all ranges.
    pub total_size: u64,
    /// Total guest pages across all ranges.
    pub total_pages: u64,
}

/// Structural validation failures for a pre-fault request.
#[derive(Debug, thiserror::Error, displaydoc::Display)]
pub enum PreFaultMemoryValidationError {
    /// pre-fault memory request must contain at least one range
    EmptyRanges,
    /// pre-fault memory range {0} has a zero size
    ZeroSize(usize),
    /// pre-fault memory range {0} GPA and size must be aligned to the 4096-byte KVM page size
    Unaligned(usize),
    /// pre-fault memory range {0} address arithmetic overflowed
    AddressOverflow(usize),
    /// pre-fault memory request total size overflowed
    TotalSizeOverflow,
    /// pre-fault memory request total page count overflowed
    TotalPagesOverflow,
}

/// Errors returned while validating or executing a pre-fault request.
#[derive(Debug, thiserror::Error, displaydoc::Display)]
pub enum PreFaultMemoryError {
    /// Invalid pre-fault memory request: {0}
    Validation(#[from] PreFaultMemoryValidationError),
    /// pre-fault memory range {0} is not fully backed by plugged guest RAM
    NotGuestRam(usize),
    /// pre-fault memory requires a paused VM (current state: {0})
    VmNotPaused(VmState),
    /// pre-fault memory is unsupported on aarch64
    UnsupportedArchitecture,
    /// pre-fault memory is unsupported: KVM_CAP_PRE_FAULT_MEMORY is unavailable
    CapabilityMissing,
    /// pre-fault memory cannot run because no vCPU is available
    NoVcpus,
    /// failed to send pre-fault work to vCPU {vcpu_id}: {source}
    VcpuSend {
        /// vCPU that could not receive the work.
        vcpu_id: usize,
        /// Event-send failure.
        #[source]
        source: VcpuSendEventError,
    },
    /// pre-fault memory failed on vCPU {vcpu_id}: {source}
    Vcpu {
        /// vCPU that reported the failure.
        vcpu_id: usize,
        /// Failure reported by the vCPU thread.
        #[source]
        source: VcpuError,
    },
    /// pre-fault memory received an unexpected response from vCPU {vcpu_id}: {reason}
    UnexpectedResponse {
        /// vCPU that returned the response.
        vcpu_id: usize,
        /// Explanation of the unexpected response.
        reason: String,
    },
}

/// Errors returned by the `KVM_PRE_FAULT_MEMORY` wrapper.
#[derive(Debug, thiserror::Error, displaydoc::Display)]
pub enum PreFaultMemoryIoctlError {
    /// KVM_PRE_FAULT_MEMORY failed at GPA {gpa:#x}: errno {errno} ({error}); {size} bytes remain
    Ioctl {
        /// GPA returned by the kernel when the ioctl failed.
        gpa: u64,
        /// Remaining bytes returned by the kernel when the ioctl failed.
        size: u64,
        /// Numeric errno returned by the kernel.
        errno: i32,
        /// Operating-system error returned by the ioctl.
        #[source]
        error: io::Error,
    },
    /// KVM_PRE_FAULT_MEMORY made no progress at GPA {gpa:#x}; {size} bytes remain
    NoProgress {
        /// GPA returned by the kernel.
        gpa: u64,
        /// Remaining bytes returned by the kernel.
        size: u64,
    },
    /// KVM_PRE_FAULT_MEMORY is unavailable on this architecture
    Unsupported,
}

#[cfg(target_arch = "x86_64")]
const _: [(); 64] = [(); size_of::<kvm_pre_fault_memory>()];

impl PreFaultMemoryRequest {
    /// Validates request shape and computes checked aggregate sizes.
    pub fn validate(&self) -> Result<PreFaultMemoryStats, PreFaultMemoryValidationError> {
        if self.ranges.is_empty() {
            return Err(PreFaultMemoryValidationError::EmptyRanges);
        }

        let page_size = u64::try_from(GUEST_PAGE_SIZE).expect("guest page size exceeds u64");
        let mut total_size = 0u64;
        let mut total_pages = 0u64;

        for (index, range) in self.ranges.iter().enumerate() {
            if range.size == 0 {
                return Err(PreFaultMemoryValidationError::ZeroSize(index));
            }
            if !range.gpa.is_multiple_of(page_size) || !range.size.is_multiple_of(page_size) {
                return Err(PreFaultMemoryValidationError::Unaligned(index));
            }
            if range.gpa.checked_add(range.size).is_none() {
                return Err(PreFaultMemoryValidationError::AddressOverflow(index));
            }

            total_size = total_size
                .checked_add(range.size)
                .ok_or(PreFaultMemoryValidationError::TotalSizeOverflow)?;
            total_pages = total_pages
                .checked_add(range.size / page_size)
                .ok_or(PreFaultMemoryValidationError::TotalPagesOverflow)?;
        }

        Ok(PreFaultMemoryStats {
            total_size,
            total_pages,
        })
    }
}

/// Splits validated ranges into balanced, page-aligned vCPU work queues.
pub fn split_pre_fault_ranges(
    ranges: &[PreFaultMemoryRange],
    vcpu_count: usize,
) -> Result<Vec<Vec<PreFaultMemoryRange>>, PreFaultMemoryError> {
    let request = PreFaultMemoryRequest {
        ranges: ranges.to_vec(),
    };
    let stats = request.validate()?;

    if vcpu_count == 0 {
        return Err(PreFaultMemoryError::NoVcpus);
    }

    let vcpu_count_u64 = u64::try_from(vcpu_count).expect("vCPU count exceeds u64");
    let worker_count = if stats.total_pages < vcpu_count_u64 {
        usize::try_from(stats.total_pages).expect("page count does not fit in usize")
    } else {
        vcpu_count
    };
    let worker_count_u64 = u64::try_from(worker_count).expect("worker count exceeds u64");
    let base_pages = stats.total_pages / worker_count_u64;
    let extra_pages = usize::try_from(stats.total_pages % worker_count_u64)
        .expect("remainder does not fit in usize");
    let mut quotas = (0..worker_count)
        .map(|worker| base_pages + u64::from(worker < extra_pages))
        .collect::<Vec<_>>();
    let mut work = vec![Vec::new(); worker_count];
    let page_size = u64::try_from(GUEST_PAGE_SIZE).expect("guest page size exceeds u64");
    let mut worker_index = 0usize;

    for (range_index, range) in ranges.iter().enumerate() {
        let mut remaining_pages = range.size / page_size;
        let mut gpa = range.gpa;

        while remaining_pages != 0 {
            while quotas[worker_index] == 0 {
                worker_index += 1;
            }
            let fragment_pages = remaining_pages.min(quotas[worker_index]);
            let fragment_size = fragment_pages * page_size;
            work[worker_index].push(PreFaultMemoryRange {
                gpa,
                size: fragment_size,
            });
            gpa = gpa
                .checked_add(fragment_size)
                .ok_or(PreFaultMemoryValidationError::AddressOverflow(range_index))?;
            remaining_pages -= fragment_pages;
            quotas[worker_index] -= fragment_pages;
        }
    }

    Ok(work)
}

/// Sends every pre-fault work queue before any response is received.
#[cfg(target_arch = "x86_64")]
pub(crate) fn send_pre_fault_events<F>(
    work: &[Vec<PreFaultMemoryRange>],
    mut send: F,
) -> Option<(usize, VcpuSendEventError)>
where
    F: FnMut(usize, Vec<PreFaultMemoryRange>) -> Result<(), VcpuSendEventError>,
{
    let mut first_error = None;

    for (vcpu_id, ranges) in work.iter().enumerate() {
        // `VcpuHandle::send_event` enqueues the event before it attempts to signal the vCPU. The
        // caller must therefore drain this worker even when this call returns an error.
        match send(vcpu_id, ranges.clone()) {
            Err(error) if first_error.is_none() => first_error = Some((vcpu_id, error)),
            _ => {}
        }
    }

    first_error
}

/// Receives every response for a pre-fault operation and returns the first response error.
#[cfg(target_arch = "x86_64")]
pub(crate) fn drain_pre_fault_responses<F>(
    worker_count: usize,
    mut receive: F,
) -> Option<PreFaultMemoryError>
where
    F: FnMut(usize) -> Result<VcpuResponse, std::sync::mpsc::RecvError>,
{
    let mut first_error = None;

    for vcpu_id in 0..worker_count {
        let response_error = match receive(vcpu_id) {
            Ok(VcpuResponse::PreFaultMemoryCompleted) => None,
            Ok(VcpuResponse::Error(source)) => Some(PreFaultMemoryError::Vcpu { vcpu_id, source }),
            Ok(VcpuResponse::NotAllowed(reason)) => {
                Some(PreFaultMemoryError::UnexpectedResponse { vcpu_id, reason })
            }
            Ok(VcpuResponse::Exited(exit_code)) => Some(PreFaultMemoryError::UnexpectedResponse {
                vcpu_id,
                reason: format!("vCPU exited with status {exit_code:?}"),
            }),
            Ok(other) => Some(PreFaultMemoryError::UnexpectedResponse {
                vcpu_id,
                reason: format!("received {other:?}"),
            }),
            Err(error) => Some(PreFaultMemoryError::UnexpectedResponse {
                vcpu_id,
                reason: format!("failed to receive vCPU response: {error}"),
            }),
        };

        if first_error.is_none() {
            first_error = response_error;
        }
    }

    first_error
}

/// Executes pre-fault ioctls for a single vCPU's work queue.
pub fn pre_fault_memory(
    vcpu_fd: &VcpuFd,
    vcpu_id: u8,
    ranges: &[PreFaultMemoryRange],
) -> Result<(), PreFaultMemoryIoctlError> {
    #[cfg(target_arch = "x86_64")]
    {
        run_pre_fault_memory(vcpu_id, ranges, |request| {
            // SAFETY: The caller invokes this function from the owning vCPU thread with a valid
            // KVM vCPU fd. `kvm_pre_fault_memory` is the bindgen representation of the UAPI
            // struct, exactly 64 bytes, and remains alive and exclusively borrowed for the
            // duration of the ioctl.
            let result = unsafe { ioctl_with_mut_ref(vcpu_fd, KVM_PRE_FAULT_MEMORY(), request) };
            if result < 0 {
                Err(io::Error::last_os_error())
            } else {
                Ok(())
            }
        })
    }

    #[cfg(target_arch = "aarch64")]
    {
        let _ = (vcpu_fd, vcpu_id, ranges);
        Err(PreFaultMemoryIoctlError::Unsupported)
    }
}

#[cfg(target_arch = "x86_64")]
const KVMIO: ::std::os::raw::c_uint = 0xAE;

#[cfg(target_arch = "x86_64")]
mod pre_fault_memory_ioctl {
    #![allow(missing_docs)]

    use super::*;

    ioctl_iowr_nr!(KVM_PRE_FAULT_MEMORY, KVMIO, 0xd5, kvm_pre_fault_memory);
}

#[cfg(target_arch = "x86_64")]
use pre_fault_memory_ioctl::KVM_PRE_FAULT_MEMORY;

#[cfg(target_arch = "x86_64")]
fn run_pre_fault_memory<F>(
    _vcpu_id: u8,
    ranges: &[PreFaultMemoryRange],
    mut ioctl: F,
) -> Result<(), PreFaultMemoryIoctlError>
where
    F: FnMut(&mut kvm_pre_fault_memory) -> io::Result<()>,
{
    for range in ranges {
        let mut request = kvm_pre_fault_memory {
            gpa: range.gpa,
            size: range.size,
            flags: 0,
            padding: [0; 5],
        };

        while request.size != 0 {
            let previous_gpa = request.gpa;
            let previous_size = request.size;
            request.flags = 0;
            request.padding = [0; 5];

            match ioctl(&mut request) {
                Err(error) if error.raw_os_error() == Some(libc::EINTR) => {
                    request.gpa = previous_gpa;
                    request.size = previous_size;
                }
                Err(error) => {
                    let errno = error.raw_os_error().unwrap_or(-1);
                    return Err(PreFaultMemoryIoctlError::Ioctl {
                        gpa: request.gpa,
                        size: request.size,
                        errno,
                        error,
                    });
                }
                Ok(()) if request.size >= previous_size => {
                    return Err(PreFaultMemoryIoctlError::NoProgress {
                        gpa: request.gpa,
                        size: request.size,
                    });
                }
                Ok(()) => {}
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    #[cfg(target_arch = "x86_64")]
    use std::collections::VecDeque;
    #[cfg(target_arch = "x86_64")]
    use std::sync::mpsc::channel;
    #[cfg(target_arch = "x86_64")]
    use std::thread;

    use super::*;
    #[cfg(target_arch = "x86_64")]
    use crate::vstate::vcpu::{VcpuError, VcpuResponse, VcpuSendEventError};
    #[cfg(target_arch = "x86_64")]
    use kvm_bindings::KVM_CAP_PRE_FAULT_MEMORY;

    fn range(gpa: u64, size: u64) -> PreFaultMemoryRange {
        PreFaultMemoryRange { gpa, size }
    }

    #[test]
    fn validates_ranges_and_totals() {
        let request = PreFaultMemoryRequest {
            ranges: vec![range(0x1000, 0x3000), range(0x9000, 0x1000)],
        };
        assert_eq!(
            request.validate().unwrap(),
            PreFaultMemoryStats {
                total_size: 0x4000,
                total_pages: 4,
            }
        );
        assert!(matches!(
            PreFaultMemoryRequest { ranges: vec![] }.validate(),
            Err(PreFaultMemoryValidationError::EmptyRanges)
        ));
        assert!(matches!(
            PreFaultMemoryRequest {
                ranges: vec![range(0, 0)]
            }
            .validate(),
            Err(PreFaultMemoryValidationError::ZeroSize(0))
        ));
        assert!(matches!(
            PreFaultMemoryRequest {
                ranges: vec![range(1, 0x1000)]
            }
            .validate(),
            Err(PreFaultMemoryValidationError::Unaligned(0))
        ));
        assert!(matches!(
            PreFaultMemoryRequest {
                ranges: vec![range(u64::MAX - 0xfff, 0x2000)]
            }
            .validate(),
            Err(PreFaultMemoryValidationError::AddressOverflow(0))
        ));
        assert!(matches!(
            PreFaultMemoryRequest {
                ranges: vec![range(0, u64::MAX - 0xfff), range(0, u64::MAX - 0xfff),]
            }
            .validate(),
            Err(PreFaultMemoryValidationError::TotalSizeOverflow)
        ));
    }

    #[test]
    fn balances_pages_without_reordering_or_merging() {
        let ranges = vec![range(0, 0x5000), range(0x10000, 0x1000)];
        let work = split_pre_fault_ranges(&ranges, 3).unwrap();
        assert_eq!(work.len(), 3);
        assert_eq!(work.iter().map(|worker| worker.len()).sum::<usize>(), 4);
        assert_eq!(
            work.iter()
                .map(|worker| worker.iter().map(|r| r.size / 0x1000).sum::<u64>())
                .collect::<Vec<_>>(),
            vec![2, 2, 2]
        );
        assert_eq!(work[0][0], range(0, 0x2000));
        assert_eq!(work[1][0], range(0x2000, 0x2000));
        assert_eq!(work[2][0], range(0x4000, 0x1000));
        assert_eq!(work[2][1], range(0x10000, 0x1000));
    }

    #[test]
    fn worker_count_never_exceeds_pages() {
        let ranges = [range(0, 0x2000)];
        let work = split_pre_fault_ranges(&ranges, 8).unwrap();
        assert_eq!(work.len(), 2);
        assert!(work.iter().all(|worker| !worker.is_empty()));
        assert!(matches!(
            split_pre_fault_ranges(&ranges, 0),
            Err(PreFaultMemoryError::NoVcpus)
        ));
    }

    #[test]
    fn one_vcpu_preserves_ranges_and_large_ranges_split_on_pages() {
        let ranges = vec![range(0, 0x1000), range(0x4000, 0x9000)];
        assert_eq!(
            split_pre_fault_ranges(&ranges, 1).unwrap(),
            vec![ranges.clone()]
        );

        let work = split_pre_fault_ranges(&ranges, 4).unwrap();
        assert_eq!(work.iter().flatten().map(|r| r.size).sum::<u64>(), 0xa000);
        assert!(work
            .iter()
            .flatten()
            .all(|r| r.gpa % 0x1000 == 0 && r.size % 0x1000 == 0));
        assert!(work.iter().flatten().all(|fragment| {
            ranges.iter().any(|source| {
                fragment.gpa >= source.gpa
                    && fragment.gpa + fragment.size <= source.gpa + source.size
            })
        }));
    }

    #[test]
    fn duplicate_ranges_are_preserved_without_deduplication() {
        let duplicate = range(0x2000, 0x1000);
        let work = split_pre_fault_ranges(&[duplicate.clone(), duplicate.clone()], 2).unwrap();
        assert_eq!(work, vec![vec![duplicate.clone()], vec![duplicate]]);
    }

    #[cfg(target_arch = "x86_64")]
    #[test]
    fn control_sends_all_work_before_receiving() {
        let work = vec![vec![range(0, 0x1000)], vec![range(0x1000, 0x1000)]];
        let mut sent = Vec::new();
        let mut receiving = false;

        let send_error = send_pre_fault_events(&work, |vcpu_id, _ranges| {
            assert!(!receiving);
            sent.push(vcpu_id);
            Ok(())
        });
        assert!(send_error.is_none());
        assert_eq!(sent, vec![0, 1]);

        receiving = true;
        let mut responses = VecDeque::from([
            VcpuResponse::PreFaultMemoryCompleted,
            VcpuResponse::PreFaultMemoryCompleted,
        ]);
        let response_error = drain_pre_fault_responses(work.len(), |_vcpu_id| {
            assert!(receiving);
            Ok(responses.pop_front().expect("missing test response"))
        });
        assert!(response_error.is_none());
        assert!(responses.is_empty());
    }

    #[cfg(target_arch = "x86_64")]
    #[test]
    fn signal_failure_is_recorded_and_all_queued_workers_are_drained() {
        let work = vec![
            vec![range(0, 0x1000)],
            vec![range(0x1000, 0x1000)],
            vec![range(0x2000, 0x1000)],
        ];
        let mut sent = Vec::new();
        let send_error = send_pre_fault_events(&work, |vcpu_id, _ranges| {
            sent.push(vcpu_id);
            if vcpu_id == 1 {
                Err(VcpuSendEventError(vmm_sys_util::errno::Error::new(
                    libc::EIO,
                )))
            } else {
                Ok(())
            }
        });
        assert_eq!(sent, vec![0, 1, 2]);
        assert_eq!(send_error.as_ref().map(|(vcpu_id, _)| *vcpu_id), Some(1));

        let mut first_error =
            send_error.map(|(vcpu_id, source)| PreFaultMemoryError::VcpuSend { vcpu_id, source });
        let mut responses = VecDeque::from([
            VcpuResponse::PreFaultMemoryCompleted,
            VcpuResponse::PreFaultMemoryCompleted,
            VcpuResponse::PreFaultMemoryCompleted,
        ]);
        let response_error = drain_pre_fault_responses(work.len(), |_vcpu_id| {
            Ok(responses.pop_front().expect("missing test response"))
        });
        if first_error.is_none() {
            first_error = response_error;
        }

        assert!(matches!(
            first_error,
            Some(PreFaultMemoryError::VcpuSend { vcpu_id: 1, .. })
        ));
        assert!(responses.is_empty());
    }

    #[cfg(target_arch = "x86_64")]
    #[test]
    fn response_failure_does_not_skip_other_workers() {
        let mut responses = VecDeque::from([
            VcpuResponse::Error(VcpuError::FaultyKvmExit("worker failure".to_string())),
            VcpuResponse::PreFaultMemoryCompleted,
            VcpuResponse::PreFaultMemoryCompleted,
        ]);

        let error = drain_pre_fault_responses(3, |_vcpu_id| {
            Ok(responses.pop_front().expect("missing test response"))
        });

        assert!(matches!(
            error,
            Some(PreFaultMemoryError::Vcpu { vcpu_id: 0, .. })
        ));
        assert!(responses.is_empty());
    }

    #[cfg(target_arch = "x86_64")]
    #[test]
    fn blocking_drain_leaves_next_operation_response_untouched() {
        let (release_sender, release_receiver) = channel();
        let (response_sender, response_receiver) = channel();
        let worker = thread::spawn(move || {
            release_receiver.recv().unwrap();
            response_sender
                .send(VcpuResponse::PreFaultMemoryCompleted)
                .unwrap();
            response_sender.send(VcpuResponse::Resumed).unwrap();
        });

        let mut first_receive = true;
        let error = drain_pre_fault_responses(1, |_vcpu_id| {
            assert!(first_receive);
            first_receive = false;
            release_sender.send(()).unwrap();
            response_receiver.recv()
        });

        assert!(error.is_none());
        assert!(matches!(
            response_receiver.recv().unwrap(),
            VcpuResponse::Resumed
        ));
        worker.join().unwrap();
    }

    #[test]
    #[cfg(target_arch = "x86_64")]
    fn uapi_layout_is_stable() {
        assert_eq!(size_of::<kvm_pre_fault_memory>(), 64);
        assert_eq!(std::mem::offset_of!(kvm_pre_fault_memory, gpa), 0);
        assert_eq!(std::mem::offset_of!(kvm_pre_fault_memory, size), 8);
        assert_eq!(std::mem::offset_of!(kvm_pre_fault_memory, flags), 16);
        assert_eq!(std::mem::offset_of!(kvm_pre_fault_memory, padding), 24);
        assert_eq!(KVM_CAP_PRE_FAULT_MEMORY, 236);
        assert_eq!(KVM_PRE_FAULT_MEMORY_IOCTL, 0xc040_aed5);
        #[cfg(target_arch = "x86_64")]
        assert_eq!(KVM_PRE_FAULT_MEMORY(), KVM_PRE_FAULT_MEMORY_IOCTL);
    }

    #[test]
    fn stable_state_and_capability_errors() {
        assert_eq!(
            PreFaultMemoryError::CapabilityMissing.to_string(),
            "pre-fault memory is unsupported: KVM_CAP_PRE_FAULT_MEMORY is unavailable"
        );
        assert_eq!(
            PreFaultMemoryError::VmNotPaused(VmState::Running).to_string(),
            "pre-fault memory requires a paused VM (current state: Running)"
        );
    }

    #[cfg(target_arch = "aarch64")]
    #[test]
    fn aarch64_pre_fault_is_unsupported() {
        assert_eq!(
            PreFaultMemoryError::UnsupportedArchitecture.to_string(),
            "pre-fault memory is unsupported on aarch64"
        );
        assert_eq!(
            PreFaultMemoryIoctlError::Unsupported.to_string(),
            "KVM_PRE_FAULT_MEMORY is unavailable on this architecture"
        );
    }

    #[cfg(target_arch = "x86_64")]
    #[test]
    fn ioctl_loop_handles_partial_progress_and_eintr() {
        let ranges = [range(0x1000, 0x3000)];
        let mut calls = 0;
        run_pre_fault_memory(0, &ranges, |request| {
            calls += 1;
            assert_eq!(request.flags, 0);
            assert_eq!(request.padding, [0; 5]);
            if calls == 1 {
                request.flags = u64::MAX;
                request.padding = [u64::MAX; 5];
                return Err(io::Error::from_raw_os_error(libc::EINTR));
            }
            request.flags = u64::MAX;
            request.padding = [u64::MAX; 5];
            request.gpa += 0x1000;
            request.size -= 0x1000;
            Ok(())
        })
        .unwrap();
        assert_eq!(calls, 4);
    }

    #[cfg(target_arch = "x86_64")]
    #[test]
    fn ioctl_loop_rejects_no_progress_and_propagates_errors() {
        let ranges = [range(0, 0x1000)];
        assert!(matches!(
            run_pre_fault_memory(0, &ranges, |_| Ok(())),
            Err(PreFaultMemoryIoctlError::NoProgress { .. })
        ));

        let result = run_pre_fault_memory(2, &ranges, |_| {
            Err(io::Error::from_raw_os_error(libc::EINVAL))
        });
        assert!(matches!(
            result,
            Err(PreFaultMemoryIoctlError::Ioctl {
                gpa: 0,
                size: 0x1000,
                ..
            })
        ));
    }
}
